-- 方块世界教学库：表结构
-- 可以重复执行；脚本会删除并重建 blockworld schema。

DROP SCHEMA IF EXISTS blockworld CASCADE;
CREATE SCHEMA blockworld;
SET search_path TO blockworld, public;

CREATE TABLE dimensions (
    dimension_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dimension_key text NOT NULL UNIQUE,
    display_name text NOT NULL,
    hostile boolean NOT NULL DEFAULT true
);

CREATE TABLE worlds (
    world_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    world_name text NOT NULL UNIQUE,
    seed_label text NOT NULL,
    difficulty text NOT NULL CHECK (difficulty IN ('peaceful', 'easy', 'normal', 'hard')),
    created_at date NOT NULL
);

CREATE TABLE players (
    player_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_name text NOT NULL UNIQUE,
    joined_at date NOT NULL,
    home_world_id integer NOT NULL REFERENCES worlds(world_id),
    home_dimension_id integer NOT NULL REFERENCES dimensions(dimension_id),
    xp_level integer NOT NULL DEFAULT 0 CHECK (xp_level >= 0)
);

CREATE TABLE blocks (
    block_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_name text NOT NULL UNIQUE,
    category text NOT NULL CHECK (category IN ('ore', 'building', 'food', 'redstone', 'utility', 'mob_drop')),
    rarity text NOT NULL CHECK (rarity IN ('common', 'uncommon', 'rare', 'epic')),
    is_ore boolean NOT NULL DEFAULT false,
    stack_size integer NOT NULL DEFAULT 64 CHECK (stack_size > 0)
);

CREATE TABLE gather_logs (
    gather_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id integer NOT NULL REFERENCES players(player_id),
    world_id integer NOT NULL REFERENCES worlds(world_id),
    dimension_id integer NOT NULL REFERENCES dimensions(dimension_id),
    block_id integer NOT NULL REFERENCES blocks(block_id),
    gathered_at timestamptz NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    tool text,
    x integer NOT NULL,
    y integer NOT NULL,
    z integer NOT NULL,
    note text
);

CREATE TABLE craft_recipes (
    recipe_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name text NOT NULL UNIQUE,
    station text NOT NULL CHECK (station IN ('inventory', 'crafting_table', 'furnace', 'blast_furnace', 'smithing_table', 'brewing_stand')),
    recipe_level integer NOT NULL CHECK (recipe_level BETWEEN 1 AND 5)
);

CREATE TABLE craft_logs (
    craft_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id integer NOT NULL REFERENCES players(player_id),
    recipe_id integer NOT NULL REFERENCES craft_recipes(recipe_id),
    crafted_at timestamptz NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0)
);

CREATE TABLE builds (
    build_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id integer NOT NULL REFERENCES players(player_id),
    world_id integer NOT NULL REFERENCES worlds(world_id),
    dimension_id integer NOT NULL REFERENCES dimensions(dimension_id),
    build_name text NOT NULL,
    build_type text NOT NULL,
    status text NOT NULL CHECK (status IN ('planned', 'building', 'completed')),
    started_at date NOT NULL,
    completed_at date,
    block_count integer NOT NULL CHECK (block_count > 0),
    CHECK (completed_at IS NULL OR completed_at >= started_at)
);

CREATE TABLE trades (
    trade_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id integer NOT NULL REFERENCES players(player_id),
    buyer_id integer NOT NULL REFERENCES players(player_id),
    item_name text NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    emeralds integer NOT NULL CHECK (emeralds >= 0),
    traded_at timestamptz NOT NULL,
    CHECK (seller_id <> buyer_id)
);

CREATE TABLE quests (
    quest_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id integer NOT NULL REFERENCES players(player_id),
    quest_name text NOT NULL,
    status text NOT NULL CHECK (status IN ('accepted', 'completed', 'abandoned')),
    reward_xp integer NOT NULL CHECK (reward_xp >= 0),
    completed_at date
);

CREATE TABLE inventory_snapshots (
    snapshot_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id integer NOT NULL REFERENCES players(player_id),
    snapshot_at timestamptz NOT NULL,
    items jsonb NOT NULL CHECK (jsonb_typeof(items) = 'object')
);

CREATE INDEX idx_gather_logs_player_time ON gather_logs (player_id, gathered_at);
CREATE INDEX idx_gather_logs_block_time ON gather_logs (block_id, gathered_at);
CREATE INDEX idx_trades_time ON trades (traded_at);
CREATE INDEX idx_inventory_snapshots_items ON inventory_snapshots USING gin (items);

COMMENT ON SCHEMA blockworld IS 'PostgreSQL 学习用方块世界数据集';
COMMENT ON TABLE gather_logs IS '玩家采集方块的事件日志，一行代表一次记录';
COMMENT ON TABLE inventory_snapshots IS '使用 JSONB 保存某一时刻的背包摘要';
